language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --quiet --requirement requirements.txt
script:
  - make format-check
  - make unittest
  - make publish
branches:
  only: [master]
